# Deployment process
# Specify node running on alpine linux
FROM node:alpine
# Copy program all program files into /app directroy
COPY . /app
# Prefix the working directory
WORKDIR /app
# Run the app.js file in node
CMD node app.js