name: Using Env Vars

env:
  USER: "Rick"

on: workflow_dispatch
jobs:
  job-1:
    name: Say hello
    runs-on: ubuntu-latest
    env:
      JOB_USER: "job 1 user"
    steps: 
      - name: use echo to say hello
        run: echo "hello {{ env.USER }}"
      - name: echo our JOB_USER
        run: echo "hello {{ env.USER }}"
      - name: use a step variable
        run: echo "hello {{ env.USER }}"