name: Using Env Vars

env:
  USER: "Rick"

on: issues
jobs:
  job-1:
    name: Say hello
    runs-on: ubuntu-latest
    env:
      JOB_USER: "job 1 user"
    steps: 
      - name: use echo to say hello
        run: echo "hello $USER"
      - name: echo our JOB_USER
        run: echo "hello $JOB_USER"
      - name: use a step variable
        env:
          STEP_USER: "step 1 user"
        run: echo "hello $STEP_USER"
      - name: try to use above step var
        run: echo "another hello $STEP_USER"     


  job-2:
    name: Say goodbye using echo
    runs-on: ubuntu-latest
    steps: 
      - name: use echo to say goodbye
        run: echo "Goodbye $USER"
      - name: echo our JOB_USER
        run: echo "hello $JOB_USER"

